### ISSUE TITLE
feature request: please don't require captchas for register new nicks

### ISSUE THREAD

**Issue by sc0w** [oftc/oftc#5]
Please don't require to solve captchas for register new nicks

There are a lot of other irc networks which doesn't require to solve captchas.

Thanks!

**Comment by df7cb** [comment]
We will be switching from google to hcapchas soon which should fix most of the problems people have with google.

**Comment by rnowak** [comment]
The above mentioned replacement has now been deployed: https://github.com/oftc/oftc-webverify

More information can be found under the September 2021 news items over at https://www.oftc.net/
