### ISSUE TITLE
https://oftc.net/AntiSpamBot/ contains links to dead sites

### ISSUE THREAD

**Issue by matkoniecz** [oftc/oftc#6]
https://oftc.net/AntiSpamBot/

in particular, `https://isfreenodedeadyet.com/` has now some ads (or maybe is a legitimate website of actual company)

**Comment by df7cb** [comment]
Thanks, fixed in https://github.com/oftc/oftc-web/commit/cd5cf9a46801aeadf31b558216fbf004ecbb5c94.
