### ISSUE TITLE
ircs://irc.oftc.net:6697

### ISSUE THREAD

**Issue by Axelmj2006** [oftc/oftc#8]

**Comment by Axelmj2006** [comment]
@Axelmj2006

**Comment by Axelmj2006** [comment]
[](url)

**Comment by Axelmj2006** [comment]
ircs://oftcnet6xg6roj6d7id4y4cu6dchysacqj2ldgea73qzdagufflqxrid.onion:6697

**Comment by PhilienTaylor** [comment]
Hey Limbo Devs,

I don't know Axl well, but it looks like OFTC is connected to SPI, and both look like historic non-profit institutions that can help with how you'd be funding your very valuable project. The only other idea I know of is EasyRetroFunding which is as recent as the last year. SPI aids many Linux distros, and I think your work here is worthy of it. I dunno who funds QEMU, too, so maybe they'd be willing to aid you?

Thank you for everything, Limbo Devs. 🙇‍♀️
